import { createContext, useContext, useEffect, useMemo, useState } from "react";

const translations = {
  en: {
 HOME: "Home",
 SHOP: "Shop",
CATEGORIES: "Categories",
CONTACT: "Contact",
SEARCH: "Search products...",
LANG: "Language",
FEATURED_PRODUCTS: "Featured Products",

FOOTER_DESC: "Best store for little explorers",
FOOTER_NAV: "Navigation",
FOOTER_HELP: "Help",
FOOTER_SOCIAL: "Social",
FOOTER_SHIPPING: "Shipping",
FOOTER_REFUND: "Refund",
FOOTER_FAQ: "FAQ",

SLIDE_1_TITLE: "Welcome to TupTup",
SLIDE_1_SUBTITLE: "Toys, clothes & essentials for kids",
SLIDE_2_TITLE: "New Collection",
SLIDE_2_SUBTITLE: "Comfort & style for little ones",
SLIDE_3_TITLE: "Winter Sale",
SLIDE_3_SUBTITLE: "Up to 30% off",

SLIDER_BTN: "Shop Now",
ADD_TO_CART: "Add to cart",
SHOP_DESC: "Find the best products for kids",
ALL: "All",

SORT_BY: "Sort by",
PRICE_ASC: "Price ↑",
PRICE_DESC: "Price ↓",
NAME_ASC: "Name A–Z",
NAME_DESC: "Name Z–A",
LOAD_MORE: "Load more",
NOTHING_FOUND: "Nothing found 😔",
LOADING: "Loading…",
PRODUCT_LOADING: "Loading product...",
PRODUCT_NOT_FOUND: "Product not found",
BACK_TO_SHOP: "Back to shop",
CATEGORY: "Category",
ADD_TO_CART: "Add to cart",
RELATED_PRODUCTS: "You may also like",

CONTACT_TITLE: "Contact Us",
CONTACT_GET_IN_TOUCH: "Get in touch",
CONTACT_ADDRESS: "Warsaw, Poland",
CONTACT_HOURS: "Working hours",
CONTACT_WEEK: "Mon – Fri: 9:00 – 18:00",
CONTACT_WEEKEND: "Sat – Sun: Closed",
CONTACT_SUCCESS_TITLE: "Thank you!",
CONTACT_SUCCESS_TEXT_1: "Your message has been sent.",
CONTACT_SUCCESS_TEXT_2: "Our team will contact you shortly.",
CONTACT_NAME: "Your Name",
CONTACT_NAME_PH: "John Doe",
CONTACT_EMAIL: "Email Address",
CONTACT_EMAIL_PH: "email@example.com",
CONTACT_PHONE: "Phone (optional)",
CONTACT_PHONE_PH: "+48 500 200 300",
CONTACT_MESSAGE: "Message",
CONTACT_MESSAGE_PH: "Write your message here...",
CONTACT_SEND: "Send Message",
CONTACT_SENDING: "Sending...",

CHECKOUT_TITLE: "Checkout",
CHECKOUT_EMPTY: "Your cart is empty",
CHECKOUT_FILL_ALL: "Please fill in all fields",
CHECKOUT_INVALID_EMAIL: "Please enter a valid email address",
CHECKOUT_NAME: "Full Name",
CHECKOUT_NAME_PH: "John Doe",
CHECKOUT_EMAIL: "Email Address",
CHECKOUT_EMAIL_PH: "john@email.com",
CHECKOUT_EMAIL_HELP: "We’ll never share your email with anyone else.",
CHECKOUT_ADDRESS: "Delivery Address",
CHECKOUT_ADDRESS_PH: "Street, city, postal code",
CHECKOUT_TOTAL: "Total:",
CHECKOUT_PAY: "Pay now",
CHECKOUT_PROCESSING: "Processing payment…",
CHECKOUT_SUCCESS_TITLE: "Thank you for your purchase!",
CHECKOUT_SUCCESS_TEXT: "Your order has been successfully placed and paid.",
CHECKOUT_ORDER: "Order number:",
CHECKOUT_PAYMENT_CONFIRMED: "Payment confirmed",
CHECKOUT_ADMIN: "Our administrator will contact you shortly.",
CHECKOUT_NAME_REQUIRED: "Please enter your name",
CHECKOUT_EMAIL_REQUIRED: "Please enter your email",
CHECKOUT_INVALID_EMAIL: "Please enter a valid email address",
CHECKOUT_ADDRESS_REQUIRED: "Please enter delivery address",
CHECKOUT_ERROR_NAME: "Name is required",
CHECKOUT_ERROR_EMAIL: "Valid email is required",
CHECKOUT_ERROR_ADDRESS: "Address is required",
CHECKOUT_ERROR_NAME_REQUIRED: "Please enter your name",
CHECKOUT_ERROR_NAME_FORMAT: "Please enter a real name (letters only)",
CHECKOUT_ERROR_EMAIL_REQUIRED: "Please enter your email",
CHECKOUT_ERROR_EMAIL_FORMAT: "Invalid email format",
CHECKOUT_ERROR_ADDRESS_REQUIRED: "Please enter delivery address",
CHECKOUT_ERROR_ADDRESS_FORMAT: "Address must be real (min. 10 characters)",

CATEGORIES_TITLE: "Categories",
CATEGORY_TOYS: "Toys",
CATEGORY_CLOTHES: "Clothes",
CATEGORY_SHOES: "Shoes",
CATEGORY_BOOKS: "Books",

CART_EMPTY_TITLE: "Your cart is empty",
CART_EMPTY_TEXT: "Looks like you haven’t added anything yet",
CART_GO_SHOP: "Go to shop",

CART_TITLE: "Your Cart",
CART_SUMMARY: "Order Summary",
CART_ITEMS: "Items",
CART_TOTAL: "Total",
CART_CHECKOUT: "Proceed to Checkout",
NOT_FOUND_TEXT: "Sorry, the page you are looking for does not exist.",
NOT_FOUND_GO_HOME: "Go to Home",
NOTHING_FOUND_REDIRECT: "You will be redirected to the homepage in 3 seconds.",

LOGIN_TITLE: "Login",
LOGIN_SUBTITLE: "Access your account",
LOGIN_EMAIL: "Email address",
LOGIN_PASSWORD: "Password",
LOGIN_FORGOT: "Forgot your password?",
LOGIN_RESET: "Reset",
LOGIN_BTN: "Login",
LOGIN_LOADING: "Signing in...",
LOGIN_NO_ACCOUNT: "Don’t have an account?",
LOGIN_SIGNUP: "Sign up",
LOGIN_ERROR_REQUIRED: "Please fill in all fields",
LOGIN_ERROR_INVALID: "Invalid email or password",
REGISTER_ERROR_EXISTS: "User with this email already exists",

REGISTER_TITLE: "Create account",
REGISTER_BTN: "Sign up",
REGISTER_LOADING: "Creating account...",
EMAIL: "Email address",
PASSWORD: "Password",
HAVE_ACCOUNT: "Already have an account?",
LOGIN: "Login",
REGISTER_SUBTITLE: "Create your account to continue",
REGISTER_GOOGLE: "Sign up with Google",
REGISTER_BTN: "Create account",
REGISTER_LOADING: "Creating account...",
REGISTER_ERROR_REQUIRED: "Please fill in all fields",
REGISTER_ERROR_GENERIC: "Registration failed. Try again.",
LOGIN_GOOGLE_ERROR: "Google sign-in failed",
OR: "or",

CHECKOUT_SUCCESS_TITLE: "Thank you for your order!",
CHECKOUT_SUCCESS_TEXT: "Your order has been placed successfully.",
CHECKOUT_BACK_HOME: "Back to Home",
CHECKOUT_CREATE_ACCOUNT: "Create an account to track orders",
  },

  pl: {
    HOME: "Strona główna",
    SHOP: "Sklep",
    CATEGORIES: "Kategorie",
    CONTACT: "Kontakt",
    SEARCH: "Szukaj produktów...",
    LANG: "Język",

    FEATURED_PRODUCTS: "Polecane produkty",

    FOOTER_DESC: "Najlepszy sklep dla małych odkrywców",
    FOOTER_NAV: "Nawigacja",
    FOOTER_HELP: "Pomoc",
    FOOTER_SOCIAL: "Społeczność",
    FOOTER_SHIPPING: "Dostawa",
    FOOTER_REFUND: "Zwroty",
    FOOTER_FAQ: "FAQ",

SLIDE_1_TITLE: "Witamy w TupTup",
SLIDE_1_SUBTITLE: "Zabawki, ubrania i akcesoria dla dzieci",

SLIDE_2_TITLE: "Nowa kolekcja",
SLIDE_2_SUBTITLE: "Komfort i styl dla najmłodszych",

SLIDE_3_TITLE: "Zimowa wyprzedaż",
SLIDE_3_SUBTITLE: "Do 30% taniej",

SLIDER_BTN: "Kup teraz",
ADD_TO_CART: "Dodaj do koszyka",
    SHOP_TITLE: "Sklep",
    SHOP_SUBTITLE: "Znajdź najlepsze produkty dla dzieci",
    LOAD_MORE: "Pokaż więcej",
    SORT_BY: "Sortuj",
    PRICE_ASC: "Cena ↑",
    PRICE_DESC: "Cena ↓",
    NAME_ASC: "Nazwa A–Z",
    NAME_DESC: "Nazwa Z–A",
    NOTHING_FOUND: "Nic nie znaleziono 😔",
    ADD_TO_CART: "Dodaj do koszyka",
    PRODUCT_LOADING: "Ładowanie produktu...",
PRODUCT_NOT_FOUND: "Produkt nie znaleziony",
BACK_TO_SHOP: "Powrót do sklepu",
CATEGORY: "Kategoria",
ADD_TO_CART: "Dodaj do koszyka",
RELATED_PRODUCTS: "Może Ci się spodobać",
CONTACT_TITLE: "Kontakt",
CONTACT_GET_IN_TOUCH: "Skontaktuj się z nami",
CONTACT_ADDRESS: "Warszawa, Polska",
CONTACT_HOURS: "Godziny pracy",
CONTACT_WEEK: "Pn – Pt: 9:00 – 18:00",
CONTACT_WEEKEND: "Sb – Nd: Zamknięte",
CONTACT_SUCCESS_TITLE: "Dziękujemy!",
CONTACT_SUCCESS_TEXT_1: "Twoja wiadomość została wysłana.",
CONTACT_SUCCESS_TEXT_2: "Skontaktujemy się wkrótce.",
CONTACT_NAME: "Twoje imię",
CONTACT_NAME_PH: "Jan Kowalski",
CONTACT_EMAIL: "Adres email",
CONTACT_EMAIL_PH: "email@przyklad.pl",
CONTACT_PHONE: "Telefon (opcjonalnie)",
CONTACT_PHONE_PH: "+48 500 200 300",
CONTACT_MESSAGE: "Wiadomość",
CONTACT_MESSAGE_PH: "Wpisz swoją wiadomość...",
CONTACT_SEND: "Wyślij wiadomość",
CONTACT_SENDING: "Wysyłanie...",
CHECKOUT_TITLE: "Realizacja zamówienia",
CHECKOUT_EMPTY: "Twój koszyk jest pusty",
CHECKOUT_FILL_ALL: "Proszę wypełnić wszystkie pola",
CHECKOUT_INVALID_EMAIL: "Proszę wpisać prawidłowy adres email",
CHECKOUT_NAME: "Pełne imię",
CHECKOUT_NAME_PH: "Jan Kowalski",
CHECKOUT_EMAIL: "Adres email",
CHECKOUT_EMAIL_PH: "jan@przyklad.pl",
CHECKOUT_EMAIL_HELP: "Nigdy nie udostępniamy Twojego emaila nikomu innemu.",
CHECKOUT_ADDRESS: "Adres dostawy",
CHECKOUT_ADDRESS_PH: "Ulica, miasto, kod pocztowy",
CHECKOUT_TOTAL: "Razem:",
CHECKOUT_PAY: "Zapłać teraz",
CHECKOUT_PROCESSING: "Przetwarzanie płatności…",
CHECKOUT_SUCCESS_TITLE: "Dziękujemy za zakupy!",
CHECKOUT_SUCCESS_TEXT: "Twoje zamówienie zostało pomyślnie złożone i opłacone.",
CHECKOUT_ORDER: "Numer zamówienia:",
CHECKOUT_PAYMENT_CONFIRMED: "Płatność potwierdzona",
CHECKOUT_ADMIN: "Nasz administrator skontaktuje się z Tobą wkrótce.",
CHECKOUT_NAME_REQUIRED: "Podaj imię",
CHECKOUT_EMAIL_REQUIRED: "Podaj adres email",
CHECKOUT_INVALID_EMAIL: "Nieprawidłowy adres email",
CHECKOUT_ADDRESS_REQUIRED: "Podaj adres dostawy",
CHECKOUT_SUCCESS_TITLE: "Dziękujemy za zakupy!",
CHECKOUT_SUCCESS_TEXT: "Twoje zamówienie zostało pomyślnie złożone i opłacone.",
CHECKOUT_BACK_HOME: "Powrót do strony głównej",
CHECKOUT_CREATE_ACCOUNT: "Utwórz konto, aby śledzić zamówienia",
CHECKOUT_ERROR_NAME: "Imię jest wymagane",
CHECKOUT_ERROR_EMAIL: "Wymagany jest prawidłowy email",
CHECKOUT_ERROR_ADDRESS: "Wymagany jest adres",
CHECKOUT_ERROR_NAME_REQUIRED: "Wprowadź imię",
CHECKOUT_ERROR_NAME_FORMAT: "Wprowadź prawdziwe imię (tylko litery)",
CHECKOUT_ERROR_EMAIL_REQUIRED: "Wprowadź email",
CHECKOUT_ERROR_EMAIL_FORMAT: "Nieprawidłowy format email",
CHECKOUT_ERROR_ADDRESS_REQUIRED: "Wprowadź adres dostawy",
CHECKOUT_ERROR_ADDRESS_FORMAT: "Adres musi być prawdziwy (min. 10 znaków)",

CATEGORIES_TITLE: "Kategorie",
CATEGORY_TOYS: "Zabawki",
CATEGORY_CLOTHES: "Ubrania",
CATEGORY_SHOES: "Buty",
CATEGORY_BOOKS: "Książki",

CART_EMPTY_TITLE: "Twój koszyk jest pusty",
CART_EMPTY_TEXT: "Wygląda na to, że nic jeszcze nie dodałeś",
CART_GO_SHOP: "Przejdź do sklepu",
CART_TITLE: "Twój koszyk",
CART_SUMMARY: "Podsumowanie zamówienia",
CART_ITEMS: "Produkty",
CART_TOTAL: "Suma",
CART_CHECKOUT: "Przejdź do kasy",
NOT_FOUND_TEXT: "Przepraszamy, strona której szukasz nie istnieje.",
NOT_FOUND_GO_HOME: "Idź do strony głównej",
NOTHING_FOUND_REDIRECT: "Zostaniesz przekierowany na stronę główną za 3 sekundy.",

LOGIN_TITLE: "Zaloguj się do swojego konta",  
LOGIN_SUBTITLE: "Uzyskaj dostęp do swojego konta",
LOGIN_EMAIL: "Adres e-mail",
LOGIN_PASSWORD: "Hasło",
LOGIN_FORGOT: "Zapomniałeś hasła?",
LOGIN_RESET: "Resetuj",
LOGIN_BTN: "Zaloguj się",
LOGIN_LOADING: "Logowanie...",
LOGIN_NO_ACCOUNT: "Nie masz konta?",
LOGIN_SIGNUP: "Zarejestruj się",
LOGIN_ERROR_REQUIRED: "Proszę wypełnić wszystkie pola",
LOGIN_ERROR_INVALID: "Nieprawidłowy email lub hasło",
REGISTER_ERROR_EXISTS: "Użytkownik z tym emailem już istnieje",


REGISTER_TITLE: "Utwórz konto",
REGISTER_BTN: "Zarejestruj się",
REGISTER_LOADING: "Tworzenie konta...",
EMAIL: "Adres e-mail",
PASSWORD: "Hasło",
HAVE_ACCOUNT: "Masz już konto?",
LOGIN: "Zaloguj się",
REGISTER_SUBTITLE: "Utwórz konto, aby kontynuować",
REGISTER_GOOGLE: "Zarejestruj się przez Google",
REGISTER_BTN: "Utwórz konto",
REGISTER_LOADING: "Tworzenie konta...",
REGISTER_ERROR_REQUIRED: "Proszę wypełnić wszystkie pola",
REGISTER_ERROR_GENERIC: "Rejestracja nie powiodła się. Spróbuj ponownie.",
LOGIN_GOOGLE_ERROR: "Logowanie przez Google nie powiodło się",
OR: "lub",

  },
    uk: {
    HOME: "Головна",
    SHOP: "Магазин",
    CATEGORIES: "Категорії",
    CONTACT: "Контакти",
    SEARCH: "Пошук товарів...",
    LANG: "Мова",

    FEATURED_PRODUCTS: "Рекомендовані товари",
    FOOTER_DESC: "Найкращий магазин для маленьких дослідників",
    FOOTER_NAV: "Навігація",
    FOOTER_HELP: "Допомога",
    FOOTER_SOCIAL: "Соцмережі",
    FOOTER_SHIPPING: "Доставка",
    FOOTER_REFUND: "Повернення",
    FOOTER_FAQ: "FAQ",

SLIDE_1_TITLE: "Ласкаво просимо до TupTup",
SLIDE_1_SUBTITLE: "Іграшки, одяг та все для дітей",
SLIDE_2_TITLE: "Нова колекція",
SLIDE_2_SUBTITLE: "Комфорт і стиль для малечі",
SLIDE_3_TITLE: "Зимовий розпродаж",
SLIDE_3_SUBTITLE: "Знижки до 30%",

SLIDER_BTN: "До магазину",
ADD_TO_CART: "Додати в кошик",
    SHOP_TITLE: "Магазин",
    SHOP_SUBTITLE: "Знайдіть найкращі товари для дітей",
    LOAD_MORE: "Показати ще",
    SORT_BY: "Сортувати",
    PRICE_ASC: "Ціна ↑",
    PRICE_DESC: "Ціна ↓",
    NAME_ASC: "Назва A–Z",
    NAME_DESC: "Назва Z–A",
    NOTHING_FOUND: "Нічого не знайдено 😔",
    ADD_TO_CART: "Додати в кошик",
    PRODUCT_LOADING: "Завантаження товару...",
PRODUCT_NOT_FOUND: "Товар не знайдено",
BACK_TO_SHOP: "Повернутися до магазину",
CATEGORY: "Категорія",
ADD_TO_CART: "Додати в кошик",
RELATED_PRODUCTS: "Вам також може сподобатися",

CONTACT_TITLE: "Контакти",
CONTACT_GET_IN_TOUCH: "Зв’яжіться з нами",
CONTACT_ADDRESS: "Варшава, Польща",
CONTACT_HOURS: "Години роботи",
CONTACT_WEEK: "Пн – Пт: 9:00 – 18:00",
CONTACT_WEEKEND: "Сб – Нд: Зачинено",
CONTACT_SUCCESS_TITLE: "Дякуємо!",
CONTACT_SUCCESS_TEXT_1: "Ваше повідомлення надіслано.",
CONTACT_SUCCESS_TEXT_2: "Ми зв’яжемося з вами найближчим часом.",
CONTACT_NAME: "Ваше ім’я",
CONTACT_NAME_PH: "Іван Петренко",
CONTACT_EMAIL: "Електронна пошта",
CONTACT_EMAIL_PH: "email@example.com",
CONTACT_PHONE: "Телефон (необов’язково)",
CONTACT_PHONE_PH: "+48 500 200 300",
CONTACT_MESSAGE: "Повідомлення",
CONTACT_MESSAGE_PH: "Напишіть ваше повідомлення...",
CONTACT_SEND: "Надіслати",
CONTACT_SENDING: "Надсилання...",

CHECKOUT_TITLE: "Оформлення замовлення",
CHECKOUT_EMPTY: "Ваш кошик порожній",
CHECKOUT_FILL_ALL: "Будь ласка, заповніть усі поля",
CHECKOUT_INVALID_EMAIL: "Будь ласка, введіть коректну електронну адресу",

CHECKOUT_NAME: "Повне імʼя",
CHECKOUT_NAME_PH: "Іван Іваненко",
CHECKOUT_EMAIL: "Електронна пошта",
CHECKOUT_EMAIL_PH: "ivan@email.com",
CHECKOUT_EMAIL_HELP: "Ми ніколи не передаємо вашу електронну пошту третім особам.",
CHECKOUT_ADDRESS: "Адреса доставки",
CHECKOUT_ADDRESS_PH: "Вулиця, місто, поштовий індекс",
CHECKOUT_TOTAL: "Разом:",
CHECKOUT_PAY: "Оплатити",
CHECKOUT_PROCESSING: "Обробка платежу…",
CHECKOUT_SUCCESS_TITLE: "Дякуємо за покупку!",
CHECKOUT_SUCCESS_TEXT: "Ваше замовлення успішно оформлено та оплачено.",
CHECKOUT_ORDER: "Номер замовлення:",
CHECKOUT_PAYMENT_CONFIRMED: "Платіж підтверджено",
CHECKOUT_ADMIN: "Наш адміністратор звʼяжеться з вами найближчим часом.",
CHECKOUT_NAME_REQUIRED: "Введіть імʼя",
CHECKOUT_EMAIL_REQUIRED: "Введіть email",
CHECKOUT_INVALID_EMAIL: "Невірний формат email",
CHECKOUT_ADDRESS_REQUIRED: "Введіть адресу доставки",
CHECKOUT_SUCCESS_TITLE: "Дякуємо за ваше замовлення!",  
CHECKOUT_SUCCESS_TEXT: "Ваше замовлення було успішно оформлене.",
CHECKOUT_BACK_HOME: "Повернутися на головну",
CHECKOUT_CREATE_ACCOUNT: "Створіть обліковий запис для відстеження замовлень",
CHECKOUT_ERROR_NAME: "Імʼя є обовʼязковим",
CHECKOUT_ERROR_EMAIL: "Потрібен дійсний email",
CHECKOUT_ERROR_ADDRESS: "Потрібна адреса",
CHECKOUT_ERROR_NAME_REQUIRED: "Введіть імʼя",
CHECKOUT_ERROR_NAME_FORMAT: "Введіть справжнє імʼя (тільки літери)",
CHECKOUT_ERROR_EMAIL_REQUIRED: "Введіть email",
CHECKOUT_ERROR_EMAIL_FORMAT: "Невірний формат email",
CHECKOUT_ERROR_ADDRESS_REQUIRED: "Введіть адресу доставки",
CHECKOUT_ERROR_ADDRESS_FORMAT: "Адреса має бути реальною (мін. 10 символів)",

CATEGORIES_TITLE: "Категорії",
CATEGORY_TOYS: "Іграшки",
CATEGORY_CLOTHES: "Одяг",
CATEGORY_SHOES: "Взуття",
CATEGORY_BOOKS: "Книги",
CART_EMPTY_TITLE: "Ваш кошик порожній",
CART_EMPTY_TEXT: "Схоже, ви ще нічого не додали",
CART_GO_SHOP: "Перейти до магазину",

CART_TITLE: "Ваш кошик",
CART_SUMMARY: "Підсумок замовлення",
CART_ITEMS: "Товари",
CART_TOTAL: "Разом",
CART_CHECKOUT: "Перейти до оплати",
NOT_FOUND_TEXT: "Вибачте, сторінка, яку ви шукаєте, не існує.",
NOT_FOUND_GO_HOME: "Перейти на головну",
NOTHING_FOUND_REDIRECT: "Вас буде перенаправлено на головну сторінку через 3 секунди.",

LOGIN_TITLE: "Увійдіть у свій обліковий запис",  
LOGIN_SUBTITLE: "Отримайте доступ до свого облікового запису",
LOGIN_EMAIL: "Адреса електронної пошти",
LOGIN_PASSWORD: "Пароль",
LOGIN_FORGOT: "Забули пароль?",
LOGIN_RESET: "Скинути", 
LOGIN_BTN: "Увійти",
LOGIN_LOADING: "Вхід...",
LOGIN_NO_ACCOUNT: "Немає облікового запису?",
LOGIN_SIGNUP: "Зареєструватися",
LOGIN_ERROR_REQUIRED: "Будь ласка, заповніть усі поля",
LOGIN_ERROR_INVALID: "Невірний email або пароль",
REGISTER_ERROR_EXISTS: "Користувач з таким email вже існує",

REGISTER_TITLE: "Створити обліковий запис",
REGISTER_BTN: "Зареєструватися",
REGISTER_LOADING: "Створення облікового запису...", 
EMAIL: "Адреса електронної пошти",
PASSWORD: "Пароль",
HAVE_ACCOUNT: "Вже маєте обліковий запис?",
LOGIN: "Увійти",
REGISTER_SUBTITLE: "Створіть обліковий запис, щоб продовжити",
REGISTER_GOOGLE: "Зареєструватися через Google",
REGISTER_BTN: "Створити обліковий запис", 
REGISTER_LOADING: "Створення облікового запису...",
REGISTER_ERROR_REQUIRED: "Будь ласка, заповніть усі поля",
REGISTER_ERROR_GENERIC: "Реєстрація не вдалася. Спробуйте ще раз.",
LOGIN_GOOGLE_ERROR: "Вхід через Google не вдалося",
OR: "або",

  },

  ja: {
    HOME: "ホーム",
    SHOP: "ショップ",
    CATEGORIES: "カテゴリー",
    CONTACT: "お問い合わせ",
    SEARCH: "商品を検索...",
    LANG: "言語",

    FEATURED_PRODUCTS: "おすすめ商品",

    FOOTER_DESC: "小さな冒険者のための最高のお店",
    FOOTER_NAV: "ナビゲーション",
    FOOTER_HELP: "ヘルプ",
    FOOTER_SOCIAL: "ソーシャル",
    FOOTER_SHIPPING: "配送",
    FOOTER_REFUND: "返金",
    FOOTER_FAQ: "FAQ",

SLIDE_1_TITLE: "TupTupへようこそ",
SLIDE_1_SUBTITLE: "子どものためのおもちゃと洋服",
SLIDE_2_TITLE: "新コレクション",
SLIDE_2_SUBTITLE: "小さな子どもに快適さとスタイルを",
SLIDE_3_TITLE: "ウィンターセール",
SLIDE_3_SUBTITLE: "最大30%オフ",
SLIDER_BTN: "ショップへ",

ADD_TO_CART: "カートに追加",

 SHOP_TITLE: "ショップ",
 SHOP_SUBTITLE: "子供向けの最高の商品を見つけましょう",
 LOAD_MORE: "さらに表示",
 SORT_BY: "並び替え",
PRICE_ASC: "価格 ↑",
 PRICE_DESC: "価格 ↓",
 NAME_ASC: "名前 A–Z",
 NAME_DESC: "名前 Z–A",
NOTHING_FOUND: "見つかりませんでした 😔",
ADD_TO_CART: "カートに追加",
 PRODUCT_LOADING: "商品を読み込み中...",
PRODUCT_NOT_FOUND: "商品が見つかりません",
BACK_TO_SHOP: "ショップに戻る",

CATEGORY: "カテゴリー",
ADD_TO_CART: "カートに追加",
RELATED_PRODUCTS: "おすすめ商品",

CONTACT_TITLE: "お問い合わせ",
CONTACT_GET_IN_TOUCH: "お問い合わせください",
CONTACT_ADDRESS: "ポーランド、ワルシャワ",
CONTACT_HOURS: "営業時間",
CONTACT_WEEK: "月–金: 9:00 – 18:00",
CONTACT_WEEKEND: "土–日: 休業",
CONTACT_SUCCESS_TITLE: "ありがとうございます！",
CONTACT_SUCCESS_TEXT_1: "メッセージが送信されました。",
CONTACT_SUCCESS_TEXT_2: "近日中にご連絡いたします。",
CONTACT_NAME: "お名前",
CONTACT_NAME_PH: "山田 太郎",
CONTACT_EMAIL: "メールアドレス",
CONTACT_EMAIL_PH: "email@example.com",
CONTACT_PHONE: "電話番号（任意）",
CONTACT_PHONE_PH: "+48 500 200 300",
CONTACT_MESSAGE: "メッセージ",
CONTACT_MESSAGE_PH: "こちらにご記入ください...",
CONTACT_SEND: "送信",
CONTACT_SENDING: "送信中...",

CHECKOUT_TITLE: "チェックアウト",
CHECKOUT_EMPTY: "カートは空です",
CHECKOUT_FILL_ALL: "すべての項目を入力してください",
CHECKOUT_INVALID_EMAIL: "正しいメールアドレスを入力してください",
CHECKOUT_NAME: "氏名",
CHECKOUT_NAME_PH: "山田 太郎",
CHECKOUT_EMAIL: "メールアドレス",
CHECKOUT_EMAIL_PH: "taro@email.com",
CHECKOUT_EMAIL_HELP: "メールアドレスが第三者に共有されることはありません。",
CHECKOUT_ADDRESS: "配送先住所",
CHECKOUT_ADDRESS_PH: "住所、都市、郵便番号",
CHECKOUT_TOTAL: "合計：",
CHECKOUT_PAY: "今すぐ支払う",
CHECKOUT_PROCESSING: "支払い処理中…",
CHECKOUT_SUCCESS_TITLE: "ご購入ありがとうございます！",
CHECKOUT_SUCCESS_TEXT: "ご注文は正常に完了し、支払いが確認されました。",
CHECKOUT_ORDER: "注文番号：",
CHECKOUT_PAYMENT_CONFIRMED: "支払い確認済み",
CHECKOUT_ADMIN: "担当者より近日中にご連絡いたします。",
CHECKOUT_NAME_REQUIRED: "お名前を入力してください",
CHECKOUT_EMAIL_REQUIRED: "メールアドレスを入力してください",
CHECKOUT_INVALID_EMAIL: "有効なメールアドレスを入力してください",
CHECKOUT_ADDRESS_REQUIRED: "配送先住所を入力してください",
CHECKOUT_SUCCESS_TITLE: "ご注文ありがとうございます！",
CHECKOUT_SUCCESS_TEXT: "ご注文は正常に完了しました。",
CHECKOUT_BACK_HOME: "ホームに戻る",
CHECKOUT_CREATE_ACCOUNT: "注文を追跡するためにアカウントを作成する",
CHECKOUT_ERROR_NAME: "名前は必須です",
CHECKOUT_ERROR_EMAIL: "有効なメールアドレスが必要です",
CHECKOUT_ERROR_ADDRESS: "住所が必要です",
CHECKOUT_ERROR_NAME_REQUIRED: "お名前を入力してください",
CHECKOUT_ERROR_NAME_FORMAT: "本名を入力してください（文字のみ）",
CHECKOUT_ERROR_EMAIL_REQUIRED: "メールアドレスを入力してください",
CHECKOUT_ERROR_EMAIL_FORMAT: "無効なメール形式",
CHECKOUT_ERROR_ADDRESS_REQUIRED: "配送先住所を入力してください",
CHECKOUT_ERROR_ADDRESS_FORMAT: "住所は実在するものでなければなりません（最低10文字）",


CATEGORIES_TITLE: "カテゴリー",
CATEGORY_TOYS: "おもちゃ",
CATEGORY_CLOTHES: "服",
CATEGORY_SHOES: "靴",
CATEGORY_BOOKS: "本",

CART_EMPTY_TITLE: "カートは空です",
CART_EMPTY_TEXT: "まだ商品が追加されていません",
CART_GO_SHOP: "ショップへ行く",
CART_TITLE: "カート",
CART_SUMMARY: "注文概要",
CART_ITEMS: "商品数",
CART_TOTAL: "合計",
CART_CHECKOUT: "購入手続きへ",
NOT_FOUND_TEXT: "申し訳ありませんが、お探しのページは存在しません。",
NOT_FOUND_GO_HOME: "ホームへ戻る",
NOTHING_FOUND_REDIRECT: "3秒後にホームページにリダイレクトされます。",
LOGIN_TITLE: "ログイン",
LOGIN_SUBTITLE: "アカウントにアクセス",
LOGIN_EMAIL: "メールアドレス",
LOGIN_PASSWORD: "パスワード",
LOGIN_FORGOT: "パスワードをお忘れですか？",
LOGIN_RESET: "リセット",
LOGIN_BTN: "ログイン",
LOGIN_LOADING: "サインイン中…",
LOGIN_NO_ACCOUNT: "アカウントをお持ちでないですか？",
LOGIN_SIGNUP: "サインアップ",
LOGIN_ERROR_REQUIRED: "すべての項目を入力してください",
LOGIN_ERROR_INVALID: "無効なメールアドレスまたはパスワード",
REGISTER_ERROR_EXISTS: "このメールアドレスのユーザーは既に存在します",

REGISTER_TITLE: "アカウント作成",
REGISTER_BTN: "サインアップ",
REGISTER_LOADING: "アカウント作成中...",
EMAIL: "メールアドレス",
PASSWORD: "パスワード",
HAVE_ACCOUNT: "すでにアカウントをお持ちですか？",
LOGIN: "ログイン", 
REGISTER_SUBTITLE: "アカウントを作成して続行",
REGISTER_GOOGLE: "Googleでサインアップ",
REGISTER_BTN: "アカウントを作成", 
REGISTER_LOADING: "アカウント作成中...",
REGISTER_ERROR_REQUIRED: "すべての項目を入力してください",
REGISTER_ERROR_GENERIC: "登録に失敗しました。もう一度お試しください。",
LOGIN_GOOGLE_ERROR: "Googleサインインに失敗しました",
OR: "または", 

  },
};

const supportedLanguages = ["en", "pl", "uk", "ja"];

function detectBrowserLanguage() {
  const browserLang = (navigator.language || "en")
    .toLowerCase()
    .slice(0, 2);

  return supportedLanguages.includes(browserLang)
    ? browserLang
    : "en";
}


const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => {
    const saved = localStorage.getItem("lang");
    return saved && supportedLanguages.includes(saved)
      ? saved
      : detectBrowserLanguage();
  });

  useEffect(() => {
    localStorage.setItem("lang", lang);
  }, [lang]);

  const t = (key) =>
    translations[lang]?.[key] ??
    translations.en?.[key] ??
    key;

  const value = useMemo(
    () => ({ lang, setLang, t }),
    [lang]
  );

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) {
    throw new Error(
      "useLanguage must be used inside <LanguageProvider>"
    );
  }
  return ctx;
}